### ISSUE TITLE
监听.item 的变换事件要兼容老版本浏览器

### ISSUE THREAD

**Issue by 3vand0ng** [lvming6816077/H5FullscreenPage#2]
$('.item').on('transitionend webkitTransitionEnd', function(event){
});

modernizr.js 可以监测，或者你写个兼容都可以

**Comment by lvming6816077** [comment]
可以的

**Comment by lvming6816077** [comment]
嗯 这里可以兼容一下 但是这组件主要用于移动端的 pc上没有太多兼容

**Comment by 3vand0ng** [comment]
是的，低版本的手机要加私有前缀
